"$schema" = "https://starship.rs/config-schema.json"

format = """
[](surface0)\
$os\
$username\
[](fg:surface0 bg:red)\
$directory\
[](fg:red bg:peach)\
$git_branch\
$git_status\
[](fg:peach bg:yellow)\
$time\
[ ](fg:yellow)\
$line_break$character"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
format = "[󰣇 ]($style)"
style = "fg:text bg:surface0"
disabled = false

[username]
format = "[$user ]($style)"
style_root = "fg:text bg:surface0"
style_user = "fg:text bg:surface0"
show_always = true

[directory]
format = "[ $path ]($style)"
style = "fg:mantle bg:red"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "fg:base bg:peach"
symbol = ""

[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "fg:base bg:peach"

[time]
format = "[  $time ]($style)"
time_format = "%R"
style = "fg:mantle bg:yellow"
disabled = false

[line_break]
disabled = false

[character]
disabled = false
success_symbol = "[](bold fg:text)"
error_symbol = "[](bold fg:red)"
